### ISSUE TITLE
Show current line number instead of 0

### ISSUE THREAD

**Issue by dusans** [zklinger/RelativeLineNumbers#14]
When using vim with

```vim
set number
setglobal relativenumber
```

Vim display's the current line number instead of 0.
http://jeffkreeftmeijer.com/2013/vims-new-hybrid-line-number-mode/

It would be nice to have the same with your extension :)

**Comment by zklinger** [comment]
This feature is now available (v1.1).

*To enable absolute line number on current cursor line:*
* Tools -> Options -> Relative Line Numbers -> Cursor Line Number -> Show absolute line number -> True

*To customize fonts and colours:*
* Tools -> Options -> Fonts and Colors -> Relative Line Numbers Cursor Line
